"""Write a balanced audio-visual training config from whatever is converted in the cache.

    python scripts/make_av_config.py --out configs/av/omni3b_v2.yaml --per-task 1000 --min-records 100

Every dataset with a train split in $JEVTRAINER_CACHE/records is one task, capped at --per-task records (smaller ones
are repeated at most 3x). Datasets whose records carry a task-like meta key (question_type, task, ...) with 2-60 values
are split into one task per value. eval_only datasets are never used.
"""

from __future__ import annotations

import argparse
import collections
import json
import re
from pathlib import Path

import yaml

import jevtrainer.data.converters  # noqa: F401
from jevtrainer.data.base import cache_dir
from jevtrainer.registry import DATASETS

GROUP_KEYS = ("question_type", "task", "subtask", "category", "task_type", "qtype")
TEXT = [("boolq", "text"), ("mnli", "text"), ("agnews", "text"), ("csqa", "text")]


def newest(name: str, split: str) -> Path | None:
    files = sorted((cache_dir() / "records" / name).glob(f"{split}-cap*-v*.jsonl"), key=lambda p: p.stat().st_mtime)
    return files[-1] if files else None


def scan(path: Path) -> tuple[int, str | None, dict]:
    n, groups = 0, {k: collections.Counter() for k in GROUP_KEYS}
    with open(path, encoding="utf-8") as f:
        for line in f:
            n += 1
            meta = json.loads(line).get("meta") or {}
            for k in GROUP_KEYS:
                if meta.get(k) is not None:
                    groups[k][str(meta[k])] += 1
    for k in GROUP_KEYS:
        c = groups[k]
        if 2 <= len(c) <= 60 and sum(c.values()) == n:
            return n, k, dict(c)
    return n, None, {}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="configs/av/omni3b_v2.yaml")
    ap.add_argument("--per-task", type=int, default=1000)
    ap.add_argument("--min-records", type=int, default=100)
    ap.add_argument("--min-task", type=int, default=30, help="drop tasks (values of a group key) with fewer records")
    ap.add_argument("--exclude", default="", help="comma list of dataset names to leave out")
    ap.add_argument("--output-dir", default="runs/av/omni3b_v2")
    a = ap.parse_args()

    skip = {s for s in a.exclude.split(",") if s}
    sources, rows = [], []
    for name in sorted(DATASETS.keys()):
        spec = DATASETS.get(name)
        if spec.eval_only or name in skip or name.endswith("_val_only"):
            continue
        p = newest(name, "train")
        if p is None:
            continue
        n, key, groups = scan(p)
        if n < a.min_records:
            continue
        if key:
            small = [g for g, c in groups.items() if c < a.min_task]
            sources.append({"name": name, "group_by": key, "per_group": a.per_task, "repeat_to": a.per_task})
            kept = {g: min(c, a.per_task) for g, c in groups.items()}
            rows.append((name, spec.area, n, len(groups), sum(max(v, 0) for v in kept.values()), f"split by {key}; {len(small)} tiny"))
        else:
            sources.append({"name": name, "max_samples": a.per_task, "repeat_to": a.per_task})
            rows.append((name, spec.area, n, 1, min(n, a.per_task), ""))

    cfg = {
        "model": "Qwen/Qwen2.5-Omni-3B",
        "readout": "marker",
        "readout_options": {"video_frames": 8, "frame_max_side": 448, "audio_max_s": 30, "use_audio_in_video": True},
        "finetune": "lora",
        "lora": {"r": 32, "alpha": 64},
        "output_dir": a.output_dir,
        "dataset": sources,
        "augment": {"p_none": 0.05, "p_pack": 0.0},
        "epochs": 1,
        "lr": 1.0e-4,
        "weight_decay": 0.01,
        "warmup_ratio": 0.03,
        "batch_size": 2,
        "grad_accum": 16,
        "max_state_tokens": 4096,
        "max_length": 6144,
        "num_workers": 6,
        "grad_ckpt": False,
        "holdout": 0.02,
        "save_steps": 300,
        "report_to": "none",
        "resume": True,
    }
    Path(a.out).write_text(
        "# Generated by scripts/make_av_config.py: every dataset is one task (question types split further), "
        f"{a.per_task} records per task.\n" + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")
    tot = sum(r[4] for r in rows)
    print(f"{len(rows)} datasets, ~{tot} records (upper bound before the 3x repeat limit)")
    by_area = collections.Counter()
    for r in rows:
        by_area[r[1]] += r[4]
    print("by area:", dict(by_area))
    for r in rows:
        print(f"  {r[0]:28s} {r[1]:6s} raw={r[2]:7d} tasks={r[3]:3d} used~{r[4]:6d} {r[5]}")


if __name__ == "__main__":
    main()
