"""AI-generated video detection: real footage vs. clips made by text/image-to-video models.

* ``genvideo``   - GenVideo (Chen et al. 2024, DeMamba): 11-way source of a clip, read from a 50k-clip shard sample.
* ``genvidbench`` - GenVidBench (Ni et al. 2025): train = Pair 1 generators (MS, Pika, T2VZ, VC2) against real Vript clips,
  test = Pair 2 generators that never occur in training (CogVideo, Mora, SVD, MuseV) against real clips.

One clip, one question: "real or generated, and by which model". The label comes from the dataset's own annotation.
"""

from __future__ import annotations

import json
import math
import os
import re
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from jevtrainer.data import avkit, bizkit
from jevtrainer.data.base import DatasetSpec, choice_record, noul_record, register, rid
_WORKERS = int(os.environ.get("JEVTRAINER_AV_WORKERS", "8"))
_STATE = {"clip": "<video:1>"}

_Q_SRC = ("Is this video real footage recorded by a camera, or was it generated by an AI video model? "
          "If it was generated, which model most likely produced it?")

REAL = "Real footage filmed with a camera, not AI-generated (natural motion, sensor noise and consistent physics)"
GENERATORS = {
    "pika": "AI-generated by Pika, a commercial text/image-to-video service (smooth but often over-stylised motion)",
    "opensora": "AI-generated by Open-Sora, an open-source diffusion-transformer text-to-video model",
    "latte": "AI-generated by Latte, a latent diffusion transformer that models video as spatio-temporal tokens",
    "dynamicrafter": "AI-generated by DynamiCrafter, an image-to-video diffusion model that animates a still image",
    "svd": "AI-generated by Stable Video Diffusion (SVD), an image-to-video latent diffusion model",
    "seine": "AI-generated by SEINE, a short-to-long video diffusion model (transitions and extensions of clips)",
    "cogvideo": "AI-generated by CogVideo, a large transformer text-to-video model",
    "st2v": "AI-generated by ST2V, a text-to-video diffusion model",
    "zeroscope": "AI-generated by ZeroScope, an open watermark-free text-to-video diffusion model derived from ModelScope",
    "videocrafter": "AI-generated by VideoCrafter, an open text-to-video diffusion model",
    "modelscope": "AI-generated by ModelScope T2V, an early open text-to-video diffusion model",
    "t2vz": "AI-generated by Text2Video-Zero, which turns a text-to-image model into a zero-shot video generator",
    "vc2": "AI-generated by VideoCrafter2, an open text-to-video diffusion model trained with low-quality video and high-quality images",
    "mora": "AI-generated by Mora, a multi-agent framework that imitates Sora-style text-to-video generation",
    "musev": "AI-generated by MuseV, an infinite-length virtual-human video generator driven by a reference image",
    "sora": "AI-generated by OpenAI Sora, a commercial diffusion-transformer text-to-video model",
    "keling": "AI-generated by Kling (Keling), a commercial text/image-to-video service",
    "opensora_": "AI-generated by Open-Sora, an open-source diffusion-transformer text-to-video model",
}

_ALIAS = {"cog": "cogvideo", "ms": "modelscope", "opensora": "opensora"}


def _norm_gen(g: str) -> str:
    g = re.sub(r"[^a-z0-9]", "", str(g).lower())
    return _ALIAS.get(g, g)


def _criteria(gens: list[str]) -> dict[str, str]:
    return {"real": REAL, **{g: GENERATORS[g] for g in gens}}


def _record(name: str, split: str, key: str, media: dict, gen: str, gens: list[str], **meta):
    gen = "real" if gen == "real" else gen
    if gen != "real" and gen not in gens:
        return None
    rec = choice_record(rid(name, split, key), dict(_STATE), _Q_SRC, _criteria(gens), gen, name="source",
                        area="video", is_ai_generated=int(gen != "real"), generator=gen, **meta)
    rec.media = [media]
    return rec


# ---- GenVideo ---------------------------------------------------------------------------------------------
_GV_REPO = "sshaiton/GenVideo-50k-shard"
_GV_SHARDS = 84
_GV_TEST = range(79, 84)  # the last five shards (6%) are the held-out test split
_GV_GENS = ["pika", "opensora", "latte", "dynamicrafter", "svd", "seine", "cogvideo", "st2v", "zeroscope", "videocrafter"]


def genvideo(split, cap, rng):
    shards = list(_GV_TEST) if split == "test" else [i for i in range(_GV_SHARDS) if i not in _GV_TEST]
    rng.shuffle(shards)
    per = 1000
    n = max(1, min(len(shards), math.ceil(cap / per)))
    shards = shards[:n]
    quota = math.ceil(cap / n)
    stop = bizkit.deadline()

    def accept(stem, side, member):
        d = json.loads(side) if side else {}
        gen = _norm_gen(d.get("generator") or re.sub(r"^\d+_", "", stem).split("_")[0].split("-")[0])
        if gen not in _GV_GENS + ["real"]:
            return None
        return stem, gen

    def one(i):
        return bizkit.stream_tar_videos(_GV_REPO, f"dataset_shard_{i:06d}.tar", "genvideo", accept, quota, workers=1, stop_at=stop)

    with ThreadPoolExecutor(min(_WORKERS, n)) as ex:
        parts = list(ex.map(one, shards))
    items = [(k, v) for p in parts for k, v in p.items()]
    rng.shuffle(items)
    for key, (gen, media) in items[:cap]:
        rec = _record("genvideo", split, key, media, gen, _GV_GENS)
        if rec:
            yield rec


register(DatasetSpec("genvideo", genvideo, ("train", "test"), _GV_REPO, "mit (GenVideo: research use)", "video", multimodal=True,
                     description="GenVideo: real footage vs. 10 AI video generators (which one?); test = 5 held-out shards"))


# ---- GenVidBench ------------------------------------------------------------------------------------------
_GVB_REPO = "jian-0/GenVidBench"
_GVB_TRAIN = {"ms": "GenVidBench/Pair1/ms.rar", "pika": "GenVidBench/Pair1/pika.rar", "t2vz": "GenVidBench/Pair1/t2vz.rar",
              "vc2": "GenVidBench/Pair1/vc2.rar"}
_GVB_TEST = {"cogvideo": "GenVidBench/Pair2/cogvideo.rar", "mora": "GenVidBench/Pair2/mora.rar", "svd": "GenVidBench/Pair2/svd.rar",
             "musev": "GenVidBench/Pair2/musev.rar"}
_GVB_REAL = "GenVidBench/Pair1/vript.rar"
_GVB_REAL_FILES = int(os.environ.get("JEVTRAINER_GVB_REAL", "1500"))
_Q_AI = "Was this video generated by an AI video model rather than recorded by a camera?"
_AI_TRUE = "AI-generated: synthesized by a video diffusion / transformer model (temporal flicker, warped objects, implausible motion)"
_AI_FALSE = "Real: a clip recorded with a camera and cut from an online video (consistent physics, natural motion and noise)"


def _convert_rar(rar: str, tag: str, nfiles: int, stop, max_mb: int = 40000) -> dict[str, tuple]:
    """First `nfiles` complete clips of one archive -> {key: (clip file name, media item)}; raw files are removed."""
    import shutil

    from jevtrainer.data import vidkit

    root = bizkit.stream_rar(_GVB_REPO, rar, "genvidbench", max_mb, tag, stop_at=stop, max_files=nfiles + 1)
    files = bizkit.complete_files(root)[:nfiles]
    jobs = {f"{tag}_{rid(f.name)}": {"src": f} for f in files}
    names = {k: j["src"].name for k, j in jobs.items()}
    items = vidkit.convert_local("genvidbench", jobs, workers=4)
    shutil.rmtree(root, ignore_errors=True)
    return {k: (names[k], v) for k, v in items.items()}


def _gvb_reals(stop) -> dict[str, tuple]:
    """Real Vript clips (the first ones of the archive), converted once and shared by both splits via a manifest."""
    from jevtrainer.data import vidkit

    man = avkit.media_dir("genvidbench", "_manifest") / "real.json"
    if man.exists():
        names = json.loads(man.read_text())
        out = {k: (n, vidkit.cached_item("genvidbench", k)) for k, n in names.items()}
        return {k: v for k, v in out.items() if v[1]}
    got = _convert_rar(_GVB_REAL, "real", _GVB_REAL_FILES, stop)
    man.write_text(json.dumps({k: v[0] for k, v in got.items()}))
    return got


def _gvb_is_test_real(clip: str) -> bool:
    return int(rid(clip.split("-Scene-")[0]), 16) % 4 == 0  # held out by source video: 25% of the real clips


def genvidbench(split, cap, rng):
    stop = bizkit.deadline()
    gens = _GVB_TEST if split == "test" else _GVB_TRAIN
    with ThreadPoolExecutor(4) as ex:
        freal = ex.submit(_gvb_reals, stop)
        ffake = {g: ex.submit(_convert_rar, rar, g, max(8, min(cap // 8, 500 if split == "train" else 150)), stop)
                 for g, rar in gens.items()}
        reals = freal.result()
        fakes = {g: f.result() for g, f in ffake.items()}
    real = [(k, v) for k, v in reals.items() if _gvb_is_test_real(v[0]) == (split == "test")]
    fake = [(k, v, g) for g, d in fakes.items() for k, v in d.items()]
    n_fake = len(fake)
    rng.shuffle(real)
    real = real[: max(cap // 2, 1)]
    fake = fake[: max(cap - len(real), 1)]
    rows = [(k, v[1], "real") for k, v in real] + [(k, v[1], g) for k, v, g in fake]
    rng.shuffle(rows)
    for key, media, gen in rows[:cap]:
        rec = noul_record(rid("genvidbench", split, key), dict(_STATE), _Q_AI, gen != "real", _AI_TRUE, _AI_FALSE,
                          area="video", generator=gen, source="genvidbench")
        rec.media = [media]
        yield rec


register(DatasetSpec("genvidbench", genvidbench, ("train", "test"), _GVB_REPO, "research use (GenVidBench)", "video", multimodal=True,
                     description="GenVidBench: AI-generated vs real video; train generators (MS, Pika, T2VZ, VC2) differ from test "
                                 "generators (CogVideo, Mora, SVD, MuseV); real clips are Vript clips split by source video"))