"""AI-generated video detection: real footage vs. clips made by text/image-to-video models.

* ``genvideo``   - GenVideo (Chen et al. 2024, DeMamba): 11-way source of a clip, read from a 50k-clip shard sample.
* ``genvidbench`` - GenVidBench (Ni et al. 2025): train = Pair 1 generators (MS, Pika, T2VZ, VC2) against real Vript clips,
  test = Pair 2 generators that never occur in training (CogVideo, Mora, SVD, MuseV) against real clips.

One clip, one question: "real or generated, and by which model". The label comes from the dataset's own annotation.
"""

from __future__ import annotations

import json
import math
import os
import re
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from jevtrainer.data import avkit, bizkit
from jevtrainer.data.base import DatasetSpec, choice_record, hf_file, register, rid
_WORKERS = int(os.environ.get("JEVTRAINER_AV_WORKERS", "8"))
_STATE = {"clip": "<video:1>"}

_Q_SRC = ("Is this video real footage recorded by a camera, or was it generated by an AI video model? "
          "If it was generated, which model most likely produced it?")

REAL = "Real footage filmed with a camera, not AI-generated (natural motion, sensor noise and consistent physics)"
GENERATORS = {
    "pika": "AI-generated by Pika, a commercial text/image-to-video service (smooth but often over-stylised motion)",
    "opensora": "AI-generated by Open-Sora, an open-source diffusion-transformer text-to-video model",
    "latte": "AI-generated by Latte, a latent diffusion transformer that models video as spatio-temporal tokens",
    "dynamicrafter": "AI-generated by DynamiCrafter, an image-to-video diffusion model that animates a still image",
    "svd": "AI-generated by Stable Video Diffusion (SVD), an image-to-video latent diffusion model",
    "seine": "AI-generated by SEINE, a short-to-long video diffusion model (transitions and extensions of clips)",
    "cogvideo": "AI-generated by CogVideo, a large transformer text-to-video model",
    "st2v": "AI-generated by ST2V, a text-to-video diffusion model",
    "zeroscope": "AI-generated by ZeroScope, an open watermark-free text-to-video diffusion model derived from ModelScope",
    "videocrafter": "AI-generated by VideoCrafter, an open text-to-video diffusion model",
    "modelscope": "AI-generated by ModelScope T2V, an early open text-to-video diffusion model",
    "t2vz": "AI-generated by Text2Video-Zero, which turns a text-to-image model into a zero-shot video generator",
    "vc2": "AI-generated by VideoCrafter2, an open text-to-video diffusion model trained with low-quality video and high-quality images",
    "mora": "AI-generated by Mora, a multi-agent framework that imitates Sora-style text-to-video generation",
    "musev": "AI-generated by MuseV, an infinite-length virtual-human video generator driven by a reference image",
    "sora": "AI-generated by OpenAI Sora, a commercial diffusion-transformer text-to-video model",
    "keling": "AI-generated by Kling (Keling), a commercial text/image-to-video service",
    "opensora_": "AI-generated by Open-Sora, an open-source diffusion-transformer text-to-video model",
}

_ALIAS = {"cog": "cogvideo", "ms": "modelscope", "opensora": "opensora"}


def _norm_gen(g: str) -> str:
    g = re.sub(r"[^a-z0-9]", "", str(g).lower())
    return _ALIAS.get(g, g)


def _criteria(gens: list[str]) -> dict[str, str]:
    return {"real": REAL, **{g: GENERATORS[g] for g in gens}}


def _record(name: str, split: str, key: str, media: dict, gen: str, gens: list[str], **meta):
    gen = "real" if gen == "real" else gen
    if gen != "real" and gen not in gens:
        return None
    rec = choice_record(rid(name, split, key), dict(_STATE), _Q_SRC, _criteria(gens), gen, name="source",
                        area="video", is_ai_generated=int(gen != "real"), generator=gen, **meta)
    rec.media = [media]
    return rec


# ---- GenVideo ---------------------------------------------------------------------------------------------
_GV_REPO = "sshaiton/GenVideo-50k-shard"
_GV_SHARDS = 84
_GV_TEST = range(79, 84)  # the last five shards (6%) are the held-out test split
_GV_GENS = ["pika", "opensora", "latte", "dynamicrafter", "svd", "seine", "cogvideo", "st2v", "zeroscope", "videocrafter"]


def genvideo(split, cap, rng):
    shards = list(_GV_TEST) if split == "test" else [i for i in range(_GV_SHARDS) if i not in _GV_TEST]
    rng.shuffle(shards)
    per = 1000
    n = max(1, min(len(shards), math.ceil(cap / per)))
    shards = shards[:n]
    quota = math.ceil(cap / n)
    stop = bizkit.deadline()

    def accept(stem, side, member):
        d = json.loads(side) if side else {}
        gen = _norm_gen(d.get("generator") or re.sub(r"^\d+_", "", stem).split("_")[0].split("-")[0])
        if gen not in _GV_GENS + ["real"]:
            return None
        return stem, gen

    def one(i):
        return bizkit.stream_tar_videos(_GV_REPO, f"dataset_shard_{i:06d}.tar", "genvideo", accept, quota, workers=1, stop_at=stop)

    with ThreadPoolExecutor(min(_WORKERS, n)) as ex:
        parts = list(ex.map(one, shards))
    items = [(k, v) for p in parts for k, v in p.items()]
    rng.shuffle(items)
    for key, (gen, media) in items[:cap]:
        rec = _record("genvideo", split, key, media, gen, _GV_GENS)
        if rec:
            yield rec


register(DatasetSpec("genvideo", genvideo, ("train", "test"), _GV_REPO, "mit (GenVideo: research use)", "video", multimodal=True,
                     description="GenVideo: real footage vs. 10 AI video generators (which one?); test = 5 held-out shards"))
